# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: First User
  admin_email: user@example.com
  admin_password: changeme
  domain_name: example.com
  secret_key_base: 20ac33dbe2e084323838200861c578e2884f4352097d12b82ce92437f3145443bc3de473c4ba576f50efa519bdedb0f2378f39de1d2337ae5c6783a71deb21e2

test:
  domain_name: example.com 
  secret_key_base: 23fbb5b59530d9a5de6b1db4d477c9372715a7f95580c036fc2abf436dc93ba25f0f461f97837e62dc3f41b034822dbac1cf5b08fb6fc31db2baf50e3e0cd995

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: <%= ENV["DOMAIN_NAME"] %>
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
